spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: foo:com.example.common.Foo1,bar:com.example.common.Bar1
        spring.json.trusted.packages: com.example.common
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
